#    ___       _    ___
#   / __| ___ | |_ |   \  ___  _ __ __  _ _
#  | (_ |/ -_)|  _|| |) |/ _ \ \ V  V /| ' \
#   \___|\___| \__||___/ \___/  \_/\_/ |_||_|

# Default Configurations

lobby:
  spawn: null
options:
  maxPlayers: 12